### ISSUE TITLE
makers serve command not working for me

### ISSUE THREAD

**Issue by rogerjbos** [Polkadot-Blockchain-Academy/pba-book#10]
I am trying to build the book for offline use. `makers install`  and `makers build` both worked fine, but when I run `makers serve` I get an error (`sh: line 1: type: mlc: not found`) and the suggested fix is to run `makers install-dev`, but that gives the error shown below (and the suggested fix for that is the same command I was running (so it is recursive lol):

error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/rogerbos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling futures-io v0.3.21
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mlc v0.16.2`, intermediate artifacts can be found at `/var/folders/_f/jx8_bq5j6z156s5v4_hwx4xc0000gp/T/cargo-installZOWg04`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] INFO - Running Task: catch-error
sh: line 1: type: mlc: not found
-e ❌ You may need to install the dev tooling. Run:

makers install-dev

Any suggested fix or workaround would be welcomed.  Thanks in advance.

**Comment by NukeManDan** [comment]
`makers serve` should not require mlc. The error for mlc to `cargo install` likely is failing as you have some issues with an older rust toolchain? Although I would not suggest trying to get that to work. What is the exact error that is thrown when using `makers s` ?

My guess is that it's related to `sed` and that should now be fixed for macos with https://github.com/Polkadot-Blockchain-Academy/pba-book/commit/e0167b8c54f2ae9c98b7610cb2034f5d8810fbf5 by using https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux
