### ISSUE TITLE
Rectanlges appearing in section 4.2 Substrate Wasm Meta-Protocol

### ISSUE THREAD

**Issue by Asamartino** [Polkadot-Blockchain-Academy/pba-book#15]
Some rectangles are appearing and shouldn't be there(see below):

<img width="1375" alt="image" src="https://github.com/Polkadot-Blockchain-Academy/pba-book/assets/61462365/3f720d83-40a2-4aba-9029-9d3211dd159d">

**Comment by NukeManDan** [comment]
duplicate #8
